#!/bin/bash
# 🔒 Automated SSL Fix Script for IVS Academy
# This script helps diagnose and provides steps to fix SSL certificate issues

echo "🔍 IVS Academy SSL Certificate Fix"
echo "=================================="

echo ""
echo "📋 Current Status Check:"
echo "------------------------"
echo "✅ Site is running on Netlify"
echo "✅ HTTP requests work fine"  
echo "❌ SSL Certificate mismatch detected"
echo "❌ Certificate serves *.netlify.app instead of ivsacademy.edu.vn"

echo ""
echo "🛠️  Fix Steps (Execute in Order):"
echo "==================================="

echo ""
echo "STEP 1: Login to Netlify Dashboard"
echo "-----------------------------------"
echo "🌐 URL: https://app.netlify.com"
echo "📧 Login with your Netlify account"
echo "🔍 Find your site (likely named 'ivsjsc' or similar)"

echo ""
echo "STEP 2: Access Domain Settings"
echo "-------------------------------"
echo "1. Click on your site from dashboard"
echo "2. Go to 'Site settings'"
echo "3. Click 'Domain management' in left sidebar"
echo "4. Look for 'Custom domains' section"

echo ""
echo "STEP 3: Configure Custom Domain"
echo "--------------------------------"
echo "Current domains should show:"
echo "  Primary: [something].netlify.app"
echo "  Custom: ivsacademy.edu.vn (if added)"
echo ""
echo "If ivsacademy.edu.vn is NOT listed:"
echo "  → Click 'Add custom domain'"
echo "  → Enter: ivsacademy.edu.vn"
echo "  → Click 'Add domain'"
echo ""
echo "If ivsacademy.edu.vn IS listed but has warning:"
echo "  → Click the domain name"
echo "  → Follow verification steps"

echo ""
echo "STEP 4: Domain Verification"
echo "----------------------------"
echo "Netlify will ask you to verify domain ownership:"
echo "📝 Option A: Add DNS TXT record"
echo "   Record: _netlify"
echo "   Value: [Netlify will provide unique value]"
echo "   TTL: 3600"
echo ""
echo "📝 Option B: Point A record to Netlify"
echo "   Record: @"
echo "   Value: 75.2.60.5"
echo "   TTL: 3600"

echo ""
echo "STEP 5: Set Primary Domain"
echo "--------------------------"
echo "1. After verification completes"
echo "2. Click 'Options' next to ivsacademy.edu.vn"
echo "3. Select 'Set as primary domain'"
echo "4. Confirm the change"

echo ""
echo "STEP 6: Enable HTTPS"
echo "---------------------"
echo "1. In Domain management section"
echo "2. Scroll to 'HTTPS' section"
echo "3. If certificate shows 'Netlify certificate':"
echo "   → Click 'Renew certificate'"
echo "4. Wait 5-15 minutes for new certificate"

echo ""
echo "STEP 7: Verification Commands"
echo "-----------------------------"
echo "After 15-30 minutes, test with these commands:"
echo ""
echo "DNS Check:"
echo "nslookup ivsacademy.edu.vn"
echo ""
echo "SSL Certificate Check:"
echo "curl -I https://ivsacademy.edu.vn"
echo ""
echo "Expected certificate subject:"
echo "Subject: CN=ivsacademy.edu.vn"
echo ""
echo "🚨 If Still Having Issues:"
echo "==========================="
echo "1. Remove custom domain completely"
echo "2. Wait 5 minutes"
echo "3. Re-add custom domain"
echo "4. Complete verification again"
echo ""
echo "Alternative: Contact Netlify Support"
echo "📧 https://app.netlify.com/support"
echo ""
echo "⏰ Expected Timeline:"
echo "====================="
echo "🔄 Domain verification: 5-15 minutes"
echo "🔄 SSL certificate generation: 5-15 minutes"  
echo "🔄 DNS propagation: 0-2 hours"
echo "🔄 Full global propagation: 24-48 hours"
echo ""
echo "📱 Test Devices After Fix:"
echo "==========================="
echo "✅ Chrome Desktop"
echo "✅ Firefox Desktop"
echo "✅ Safari Desktop"  
echo "✅ Safari Mobile (iPhone/iPad)"
echo "✅ Chrome Mobile"
echo "✅ Edge Browser"
echo ""
echo "🎯 Success Criteria:"
echo "===================="
echo "✅ No SSL warnings in any browser"
echo "✅ Green padlock icon shows"
echo "✅ Certificate shows 'ivsacademy.edu.vn'"
echo "✅ Mobile Safari works without errors"
echo ""
echo "📞 Need Help? Contact:"
echo "======================"
echo "🔧 Technical Support: Technical team"
echo "📧 Domain Support: Domain registrar"
echo "💬 Netlify Support: https://answers.netlify.com"
echo ""
echo "=================================="
echo "🔒 SSL Fix Script Complete"
echo "Start with STEP 1 above ☝️"
echo "=================================="